version: '3.9'

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    volumes:
      - ./assets/chromadb:/chroma/chroma
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: "/chroma/chroma"
      ANONYMIZED_TELEMETRY: "${ANONYMIZED_TELEMETRY:-TRUE}"
    ports:
      - 8000:8000
    networks:
      devnet:
        ipv4_address: 172.10.0.10  # Modificado para uma sub-rede mais comum
    
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./assets/mongodb/:/data/db
  
  text-to-sql:
    build: .
    container_name: text_to_sql_api
    ports:
      - "8090:8090" 
    restart: always 
    environment:
      - PYTHONUNBUFFERED=1
      - CHROMADB_HOST="localhost"
      - CHROMADB_PORT="8000"
      - APP_NAME="TEXT-TO-SQL"
      - APP_DATABASE="text-to-sql"
      - MONGO_URI="mongodb://localhost:27017"
      - MONGO_USERNAME="root"
      - MONGO_PASSWORD="example"
      - OPENAI_EMBEDDING_MODEL="text-embedding-3-small"

networks:
  devnet:
    driver: bridge
    external: true
