version: '3.9'

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    volumes:
      - ./assets/chromadb:/chroma/chroma
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: "/chroma/chroma"
      ANONYMIZED_TELEMETRY: "${ANONYMIZED_TELEMETRY:-TRUE}"
    ports:
      - 8000:8000
    networks:
      - devnet 
    
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./assets/mongodb/:/data/db
    networks:
      - devnet 
    
  
  text-to-sql:
    build: .
    container_name: text_to_sql_api
    ports:
      - "8090:8090" 
      
    depends_on:
      - mongodb
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - APP_NAME=TEXT-TO-SQL
      - APP_DATABASE=text-to-sql
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - CONNECTION_PATH=./assets/connections/connections.yaml
    volumes:
      - ./src/:/app/src/
    networks:
      - devnet 
  
  postgresdb:
    image: postgres
    container_name: postgresdb
    shm_size: 128mb
    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

    networks:
      - devnet

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
    external: true
