version: '3.9'

services:
  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    volumes:
      - ./assets/chromadb:/chroma/chroma
    environment:
      IS_PERSISTENT: "TRUE"
      PERSIST_DIRECTORY: "/chroma/chroma"
      ANONYMIZED_TELEMETRY: "${ANONYMIZED_TELEMETRY:-TRUE}"
    ports:
      - 8000:8000
    networks:
      devnet:
        ipv4_address: 172.10.0.10  # Modificado para uma sub-rede mais comum
    
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./assets/mongodb/:/data/db

networks:
  devnet:
    driver: bridge
    external: true
